import {
  Shield,
  Users,
  Contact,
  Package,
  Wrench,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Receipt,
  BarChart3,
  LifeBuoy,
  Blocks,
  Settings,
  Building2,
  CreditCard,
  Boxes,
  Ticket,
  Sliders,
  Megaphone,
  User,
  ShieldCheck,
  Briefcase,
  Truck,
  Upload,
  PlusCircle,
  Layers,
  FileSpreadsheet,
  Ruler,
  FolderTree,
  Tag,
  ShieldAlert,
  ClipboardCheck,
  FileText,
  RotateCcw,
  Store,
  FileEdit,
  Send,
  Percent,
  TrendingUp,
  ArrowLeftRight,
  Landmark,
  Flame,
  PackageCheck,
  Wallet,
  FileCheck,
  Activity,
  Code2,
  MapPin,
  Barcode,
  Printer,
} from 'lucide-react';
import type { SidebarSection, SidebarMenuItem, SidebarSubItem } from '../types/navigation.types.js';

export const OFFICIAL_NAVIGATION_CONFIG: SidebarSection[] = [
  // 01 — SUPER ADMIN
  {
    id: 'sec-super-admin',
    moduleNumber: '01',
    title: '01 — SUPER ADMIN',
    items: [
      {
        id: 'nav-super-admin',
        label: 'Super Admin',
        icon: Shield,
        scope: 'platform',
        description: 'Painel global e governança multi-empresa do OLYPS PRO',
        moduleNumber: '01',
        viewType: 'super_admin',
        children: [
          {
            id: 'sub-sa-companies',
            label: 'Todas as Empresas',
            icon: Building2,
            path: '/superadmin/empresas',
            scope: 'platform',
            description: 'Gestão, listagem e auditoria de status de todas as empresas',
            viewType: 'super_admin',
          },
          {
            id: 'sub-sa-subscriptions',
            label: 'Assinaturas',
            icon: CreditCard,
            path: '/superadmin/assinaturas',
            scope: 'platform',
            description: 'Controle de planos, vigência e faturamento de pacotes',
            viewType: 'list',
          },
          {
            id: 'sub-sa-packages',
            label: 'Pacotes de Assinatura',
            icon: Boxes,
            path: '/superadmin/pacotes',
            scope: 'platform',
            description: 'Planos de assinatura e limites de recursos disponíveis',
            viewType: 'list',
            createPath: '/superadmin/pacotes/adicionar',
          },
          {
            id: 'sub-sa-coupons',
            label: 'Cupons',
            icon: Ticket,
            path: '/superadmin/cupons',
            scope: 'platform',
            description: 'Gestão de cupons de desconto para contratação',
            viewType: 'list',
            createPath: '/superadmin/cupons/adicionar',
          },
          {
            id: 'sub-sa-settings',
            label: 'Configuração Super Admin',
            icon: Sliders,
            path: '/superadmin/configuracoes',
            scope: 'platform',
            description: 'Parâmetros globais do sistema, gateways e e-mails',
            viewType: 'settings',
          },
          {
            id: 'sub-sa-communicator',
            label: 'Comunicador',
            icon: Megaphone,
            path: '/superadmin/comunicador',
            scope: 'platform',
            description: 'Disparo de avisos, comunicados e notificações globais',
            viewType: 'form',
          },
        ],
      },
    ],
  },

  // 02 — GERENCIAMENTO DE USUÁRIOS
  {
    id: 'sec-users-mgmt',
    moduleNumber: '02',
    title: '02 — GERENCIAMENTO DE USUÁRIOS',
    items: [
      {
        id: 'nav-users-mgmt',
        label: 'Gerenciamento de Usuários',
        icon: Users,
        scope: 'company',
        description: 'Usuários da empresa, papéis RBAC e agentes comerciais',
        moduleNumber: '02',
        children: [
          {
            id: 'sub-users-list',
            label: 'Usuários',
            icon: User,
            path: '/usuarios',
            permission: 'usuarios.ler',
            scope: 'company',
            description: 'Membros da empresa e credenciais de acesso',
            viewType: 'list',
            createPath: '/usuarios/adicionar',
          },
          {
            id: 'sub-users-roles',
            label: 'Papéis',
            icon: ShieldCheck,
            path: '/usuarios/papeis',
            permission: 'usuarios.permissoes',
            scope: 'company',
            description: 'Matriz de papéis e permissões granulares',
            viewType: 'list',
            createPath: '/usuarios/papeis/adicionar',
          },
          {
            id: 'sub-users-agents',
            label: 'Agentes Comerciais',
            icon: Briefcase,
            path: '/usuarios/agentes-comerciais',
            permission: 'usuarios.ler',
            scope: 'company',
            description: 'Representantes de vendas e comissionamento',
            viewType: 'list',
            createPath: '/usuarios/agentes-comerciais/adicionar',
          },
        ],
      },
    ],
  },

  // 03 — CONTATOS
  {
    id: 'sec-contacts',
    moduleNumber: '03',
    title: '03 — CONTATOS',
    items: [
      {
        id: 'nav-contacts',
        label: 'Contatos',
        icon: Contact,
        scope: 'company',
        description: 'Fornecedores, clientes e grupos de relacionamento',
        moduleNumber: '03',
        children: [
          {
            id: 'sub-contacts-suppliers',
            label: 'Fornecedores',
            icon: Truck,
            path: '/contatos/fornecedores',
            permission: 'fornecedores.ler',
            scope: 'company',
            description: 'Base de fornecedores e distribuidores cadastrados',
            viewType: 'list',
            createPath: '/contatos/fornecedores/adicionar',
          },
          {
            id: 'sub-contacts-customers',
            label: 'Clientes',
            icon: User,
            path: '/contatos/clientes',
            permission: 'clientes.ler',
            scope: 'company',
            description: 'Clientes pessoas físicas e jurídicas',
            viewType: 'list',
            createPath: '/contatos/clientes/adicionar',
          },
          {
            id: 'sub-contacts-groups',
            label: 'Grupos de Clientes',
            icon: Users,
            path: '/contatos/grupos',
            permission: 'clientes.ler',
            scope: 'company',
            description: 'Segmentação e tabelas de preços por grupo',
            viewType: 'list',
            createPath: '/contatos/grupos/adicionar',
          },
          {
            id: 'sub-contacts-import',
            label: 'Importar Contatos',
            icon: Upload,
            path: '/contatos/importar',
            permission: 'clientes.criar',
            scope: 'company',
            description: 'Importação em lote de contatos via planilha CSV/Excel',
            viewType: 'import',
          },
        ],
      },
    ],
  },

  // 04 — PRODUTOS
  {
    id: 'sec-products',
    moduleNumber: '04',
    title: '04 — PRODUTOS',
    items: [
      {
        id: 'nav-products',
        label: 'Produtos',
        icon: Package,
        scope: 'company',
        description: 'Catálogo de itens, variações, marcas e categorias',
        moduleNumber: '04',
        children: [
          {
            id: 'sub-products-list',
            label: 'Lista de Produtos',
            icon: Package,
            path: '/produtos',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Consulta do catálogo completo de produtos',
            viewType: 'list',
            createPath: '/produtos/adicionar',
          },
          {
            id: 'sub-products-add',
            label: 'Adicionar Produto',
            icon: PlusCircle,
            path: '/produtos/adicionar',
            permission: 'produtos.criar',
            scope: 'company',
            description: 'Cadastro de novos itens com código de barras e preços',
            viewType: 'form',
            listPath: '/produtos',
          },
          {
            id: 'sub-products-print-labels',
            label: 'Imprimir etiquetas',
            icon: Barcode,
            path: '/produtos/imprimir-etiquetas',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Impressão de etiquetas de código de barras e gôndola',
            viewType: 'list',
          },
          {
            id: 'sub-products-variations',
            label: 'Variations',
            icon: Layers,
            path: '/variation-templates',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Gerenciar variações de produto',
            viewType: 'list',
            createPath: '/variation-templates',
          },
          {
            id: 'sub-products-import',
            label: 'Importar Produtos',
            icon: Upload,
            path: '/produtos/importar',
            permission: 'produtos.criar',
            scope: 'company',
            description: 'Carga em massa de itens via planilha padrão',
            viewType: 'import',
          },
          {
            id: 'sub-products-init-stock',
            label: 'Importar Estoque Inicial',
            icon: FileSpreadsheet,
            path: '/produtos/estoque-inicial',
            permission: 'estoque.ajustar',
            scope: 'company',
            description: 'Lançamento do saldo inicial de almoxarifado',
            viewType: 'import',
          },
          {
            id: 'sub-products-units',
            label: 'Unidades',
            icon: Ruler,
            path: '/produtos/unidades',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Unidades de medida (UN, KG, MT, CX, L)',
            viewType: 'list',
            createPath: '/produtos/unidades/adicionar',
          },
          {
            id: 'sub-products-categories',
            label: 'Categorias',
            icon: FolderTree,
            path: '/produtos/categorias',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Árvore de categorias e subcategorias',
            viewType: 'list',
            createPath: '/produtos/categorias/adicionar',
          },
          {
            id: 'sub-products-brands',
            label: 'Marcas',
            icon: Tag,
            path: '/produtos/marcas',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Fabricantes e marcas cadastradas',
            viewType: 'list',
            createPath: '/produtos/marcas/adicionar',
          },
          {
            id: 'sub-products-warranties',
            label: 'Garantia',
            icon: ShieldAlert,
            path: '/produtos/garantias',
            permission: 'produtos.ler',
            scope: 'company',
            description: 'Prazos e termos de garantia por tipo de produto',
            viewType: 'list',
            createPath: '/produtos/garantias/adicionar',
          },
        ],
      },
    ],
  },

  // 05 — REPARAR
  {
    id: 'sec-repair',
    moduleNumber: '05',
    title: '05 — REPARAR',
    items: [
      {
        id: 'nav-repair',
        label: 'Reparar',
        icon: Wrench,
        scope: 'company',
        description: 'Assistência técnica, folhas de trabalho, laudos e faturas',
        moduleNumber: '05',
        children: [
          {
            id: 'sub-repair-worksheets',
            label: 'Folha de Trabalho',
            icon: ClipboardCheck,
            path: '/reparos/folha-de-trabalho',
            permission: 'reparos.ler',
            scope: 'company',
            description: 'Ordens de serviço e bancada técnica em andamento',
            viewType: 'list',
            createPath: '/reparos/adicionar-folha',
          },
          {
            id: 'sub-repair-add-worksheet',
            label: 'Adicionar Folha de Trabalho',
            icon: PlusCircle,
            path: '/reparos/adicionar-folha',
            permission: 'reparos.criar',
            scope: 'company',
            description: 'Entrada de novo equipamento e triagem técnica',
            viewType: 'form',
            listPath: '/reparos/folha-de-trabalho',
          },
          {
            id: 'sub-repair-invoices',
            label: 'Lista de Faturas',
            icon: FileText,
            path: '/reparos/faturas',
            permission: 'reparos.ler',
            scope: 'company',
            description: 'Faturas e cobranças geradas a partir de reparos',
            viewType: 'list',
            createPath: '/reparos/adicionar-fatura',
          },
          {
            id: 'sub-repair-add-invoice',
            label: 'Adicionar Fatura',
            icon: PlusCircle,
            path: '/reparos/adicionar-fatura',
            permission: 'reparos.criar',
            scope: 'company',
            description: 'Emissão de fatura de prestação de serviços',
            viewType: 'form',
            listPath: '/reparos/faturas',
          },
          {
            id: 'sub-repair-brands',
            label: 'Marcas',
            icon: Tag,
            path: '/reparos/marcas',
            permission: 'reparos.ler',
            scope: 'company',
            description: 'Marcas homologadas para assistência técnica',
            viewType: 'list',
            createPath: '/reparos/marcas/adicionar',
          },
          {
            id: 'sub-repair-settings',
            label: 'Configurações',
            icon: Settings,
            path: '/reparos/configuracoes',
            permission: 'reparos.configurar',
            scope: 'company',
            description: 'Modelos de checklist, termos de aceite e status de OS',
            viewType: 'settings',
          },
        ],
      },
    ],
  },

  // 06 — COMPRAS
  {
    id: 'sec-purchases',
    moduleNumber: '06',
    title: '06 — COMPRAS',
    items: [
      {
        id: 'nav-purchases',
        label: 'Compras',
        icon: ShoppingBag,
        scope: 'company',
        description: 'Aquisição de suprimentos, faturas e devoluções a fornecedores',
        moduleNumber: '06',
        children: [
          {
            id: 'sub-purchases-list',
            label: 'Lista de Compras',
            icon: ShoppingBag,
            path: '/compras',
            permission: 'compras.ler',
            scope: 'company',
            description: 'Notas de entrada e pedidos de compra efetuados',
            viewType: 'list',
            createPath: '/compras/adicionar',
          },
          {
            id: 'sub-purchases-add',
            label: 'Adicionar Compra',
            icon: PlusCircle,
            path: '/compras/adicionar',
            permission: 'compras.criar',
            scope: 'company',
            description: 'Lançamento de aquisição e atualização de estoque',
            viewType: 'form',
            listPath: '/compras',
          },
          {
            id: 'sub-purchases-returns',
            label: 'Lista de Retorno de Compras',
            icon: RotateCcw,
            path: '/compras/retorno',
            permission: 'compras.ler',
            scope: 'company',
            description: 'Devoluções de mercadorias para fornecedores',
            viewType: 'list',
            createPath: '/compras/retorno/adicionar',
          },
        ],
      },
    ],
  },

  // 07 — VENDER
  {
    id: 'sec-sales',
    moduleNumber: '07',
    title: '07 — VENDER',
    items: [
      {
        id: 'nav-sales',
        label: 'Vender',
        icon: ShoppingCart,
        scope: 'company',
        description: 'Vendas, faturamento, frente de caixa (PDV), cotações e remessas',
        moduleNumber: '07',
        children: [
          {
            id: 'sub-sales-all',
            label: 'Todas as Vendas',
            icon: ShoppingCart,
            path: '/vendas',
            permission: 'vendas.ler',
            scope: 'company',
            description: 'Histórico completo de pedidos faturados',
            viewType: 'list',
            createPath: '/vendas/adicionar',
          },
          {
            id: 'sub-sales-add',
            label: 'Adicionar Venda',
            icon: PlusCircle,
            path: '/vendas/adicionar',
            permission: 'vendas.criar',
            scope: 'company',
            description: 'Emissão de novo pedido de venda comercial',
            viewType: 'form',
            listPath: '/vendas',
          },
          {
            id: 'sub-sales-pos-list',
            label: 'Lista de PDV',
            icon: Store,
            path: '/vendas/pos-lista',
            permission: 'pdv.abrir',
            scope: 'company',
            description: 'Terminais de frente de caixa ativos e turnos',
            viewType: 'list',
          },
          {
            id: 'sub-sales-pos',
            label: 'PDV',
            icon: CreditCard,
            path: '/vendas/pos',
            permission: 'pdv.vender',
            scope: 'company',
            description: 'Terminal operacional de caixa rápido',
            viewType: 'pos',
          },
          {
            id: 'sub-sales-drafts',
            label: 'Adicionar Rascunho',
            icon: FileEdit,
            path: '/vendas/rascunho',
            permission: 'vendas.criar',
            scope: 'company',
            description: 'Criação de pedidos em estado de rascunho',
            viewType: 'form',
            listPath: '/vendas',
          },
          {
            id: 'sub-sales-quotes',
            label: 'Adicionar Cotação',
            icon: FileSpreadsheet,
            path: '/vendas/cotacao',
            permission: 'vendas.criar',
            scope: 'company',
            description: 'Elaboração de propostas comerciais e orçamentos',
            viewType: 'form',
            listPath: '/vendas',
          },
          {
            id: 'sub-sales-shipments',
            label: 'Remessa',
            icon: Send,
            path: '/vendas/remessas',
            permission: 'vendas.ler',
            scope: 'company',
            description: 'Despacho de mercadorias e ordens de entrega',
            viewType: 'list',
            createPath: '/vendas/remessas/adicionar',
          },
          {
            id: 'sub-sales-discounts',
            label: 'Desconto',
            icon: Percent,
            path: '/vendas/desconto',
            permission: 'vendas.configurar',
            scope: 'company',
            description: 'Tabelas de descontos comerciais e políticas promocionais',
            viewType: 'list',
            createPath: '/vendas/desconto/adicionar',
          },
        ],
      },
    ],
  },

  // 08 — AJUSTE DE ESTOQUE
  {
    id: 'sec-stock-adjust',
    moduleNumber: '08',
    title: '08 — AJUSTE DE ESTOQUE',
    items: [
      {
        id: 'nav-stock-adjust',
        label: 'Ajuste de Estoque',
        icon: SlidersHorizontal,
        scope: 'company',
        description: 'Controle de perdas, quebras, contagens físicas e inventário',
        moduleNumber: '08',
        children: [
          {
            id: 'sub-stock-list',
            label: 'Listar',
            icon: SlidersHorizontal,
            path: '/estoque/ajustes',
            permission: 'estoque.visualizar',
            scope: 'company',
            description: 'Histórico de lançamentos e correções de saldo',
            viewType: 'list',
            createPath: '/estoque/ajustes/adicionar',
          },
          {
            id: 'sub-stock-settings',
            label: 'Configurações de Estoque',
            icon: Settings,
            path: '/estoque/configuracoes',
            permission: 'estoque.configurar',
            scope: 'company',
            description: 'Pontos de reposição, locais de depósito e alertas',
            viewType: 'settings',
          },
          {
            id: 'sub-stock-add-adjust',
            label: 'Adicionar Ajuste de Estoque',
            icon: PlusCircle,
            path: '/estoque/ajustes/adicionar',
            permission: 'estoque.ajustar',
            scope: 'company',
            description: 'Correção manual de quantidades de itens',
            viewType: 'form',
            listPath: '/estoque/ajustes',
          },
        ],
      },
    ],
  },

  // 09 — DESPESA
  {
    id: 'sec-expenses',
    moduleNumber: '09',
    title: '09 — DESPESA',
    items: [
      {
        id: 'nav-expenses',
        label: 'Despesa',
        icon: Receipt,
        scope: 'company',
        description: 'Controle de custos operacionais, despesas e centros de custo',
        moduleNumber: '09',
        children: [
          {
            id: 'sub-expenses-list',
            label: 'Lista de Despesas',
            icon: Receipt,
            path: '/despesas',
            permission: 'financeiro.visualizar',
            scope: 'company',
            description: 'Lançamentos de contas pagas e a pagar',
            viewType: 'list',
            createPath: '/despesas/adicionar',
          },
          {
            id: 'sub-expenses-add',
            label: 'Adicionar Despesa',
            icon: PlusCircle,
            path: '/despesas/adicionar',
            permission: 'financeiro.criar',
            scope: 'company',
            description: 'Registro de novo desembolso com comprovante',
            viewType: 'form',
            listPath: '/despesas',
          },
          {
            id: 'sub-expenses-categories',
            label: 'Categoria de Despesa',
            icon: FolderTree,
            path: '/despesas/categorias',
            permission: 'financeiro.configurar',
            scope: 'company',
            description: 'Plano de contas e categorias de custos',
            viewType: 'list',
            createPath: '/despesas/categorias/adicionar',
          },
        ],
      },
    ],
  },

  // 10 — RELATÓRIOS
  {
    id: 'sec-reports',
    moduleNumber: '10',
    title: '10 — RELATÓRIOS',
    items: [
      {
        id: 'nav-reports',
        label: 'Relatórios',
        icon: BarChart3,
        scope: 'company',
        description: 'Painéis analíticos, DRE gerencial, curva ABC e auditoria',
        moduleNumber: '10',
        children: [
          {
            id: 'sub-rep-profit-loss',
            label: 'Relatório de Lucros / Perdas',
            icon: TrendingUp,
            path: '/relatorios/lucros-perdas',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Demonstrativo de resultado e margens por período',
            viewType: 'report',
          },
          {
            id: 'sub-rep-purchases-sales',
            label: 'Relatório de Compras e Vendas',
            icon: ArrowLeftRight,
            path: '/relatorios/compras-vendas',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Balanço comparativo entre entradas e saídas',
            viewType: 'report',
          },
          {
            id: 'sub-rep-tax',
            label: 'Relatório Fiscal',
            icon: Landmark,
            path: '/relatorios/fiscal',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Apuração de tributos (ICMS, PIS, COFINS, ISS)',
            viewType: 'report',
          },
          {
            id: 'sub-rep-supp-cust',
            label: 'Relatório de Fornecedor e Cliente',
            icon: Users,
            path: '/relatorios/fornecedor-cliente',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Histórico de movimentações por parceiro comercial',
            viewType: 'report',
          },
          {
            id: 'sub-rep-cust-groups',
            label: 'Relatório de Grupos de Clientes',
            icon: Contact,
            path: '/relatorios/grupos-clientes',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Desempenho de vendas agrupado por segmento',
            viewType: 'report',
          },
          {
            id: 'sub-rep-stock',
            label: 'Relatório de Estoque',
            icon: Boxes,
            path: '/relatorios/estoque',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Posição valorizada de estoque e giro de itens',
            viewType: 'report',
          },
          {
            id: 'sub-rep-trending',
            label: 'Produtos em Tendência',
            icon: Flame,
            path: '/relatorios/produtos-tendencia',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Curva ABC de produtos mais vendidos',
            viewType: 'report',
          },
          {
            id: 'sub-rep-items',
            label: 'Relatório de Itens',
            icon: PackageCheck,
            path: '/relatorios/itens',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Rastreabilidade detalhada por item e lote',
            viewType: 'report',
          },
          {
            id: 'sub-rep-prod-purchase',
            label: 'Relatório de Compra de Produtos',
            icon: ShoppingBag,
            path: '/relatorios/compra-produtos',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Evolução de preços de custo e fornecimento',
            viewType: 'report',
          },
          {
            id: 'sub-rep-prod-sales',
            label: 'Relatório de Vendas de Produtos',
            icon: ShoppingCart,
            path: '/relatorios/vendas-produtos',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Ticket médio e volumes comercializados',
            viewType: 'report',
          },
          {
            id: 'sub-rep-payments',
            label: 'Relatório de Pagamentos',
            icon: Wallet,
            path: '/relatorios/pagamentos',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Liquidações de títulos, cartões e dinheiro',
            viewType: 'report',
          },
          {
            id: 'sub-rep-expenses',
            label: 'Relatório de Despesas',
            icon: Receipt,
            path: '/relatorios/despesas',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Composição de custos fixos e variáveis',
            viewType: 'report',
          },
          {
            id: 'sub-rep-registers',
            label: 'Relatório de Registros',
            icon: FileCheck,
            path: '/relatorios/registros',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Movimentações de caixas e sangrias registradas',
            viewType: 'report',
          },
          {
            id: 'sub-rep-agents',
            label: 'Relatório de Agentes Comerciais',
            icon: Briefcase,
            path: '/relatorios/agentes-comerciais',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Comissões apuradas e metas por vendedor',
            viewType: 'report',
          },
          {
            id: 'sub-rep-activity-log',
            label: 'Registro de Atividades',
            icon: Activity,
            path: '/relatorios/registro-atividades',
            permission: 'relatorios.visualizar',
            scope: 'company',
            description: 'Trilha de auditoria e logs de ações dos usuários',
            viewType: 'report',
          },
        ],
      },
    ],
  },

  // 11 — SUPORTE
  {
    id: 'sec-support',
    moduleNumber: '11',
    title: '11 — SUPORTE',
    items: [
      {
        id: 'nav-support',
        label: 'Suporte',
        icon: LifeBuoy,
        path: '/suporte',
        scope: 'all',
        description: 'Central de ajuda, documentação técnica e abertura de chamados',
        moduleNumber: '11',
        viewType: 'custom',
      },
    ],
  },

  // 12 — MÓDULOS
  {
    id: 'sec-modules',
    moduleNumber: '12',
    title: '12 — MÓDULOS',
    items: [
      {
        id: 'nav-modules',
        label: 'Módulos',
        icon: Blocks,
        scope: 'company',
        description: 'Extensões do sistema, integrações e novas APIs',
        moduleNumber: '12',
        children: [
          {
            id: 'sub-mod-new-api',
            label: 'Novas API',
            icon: Code2,
            path: '/modulos/novas-api',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Chaves de API, webhooks e integrações de terceiros',
            viewType: 'settings',
          },
        ],
      },
    ],
  },

  // 13 — CONFIGURAÇÕES
  {
    id: 'sec-settings',
    moduleNumber: '13',
    title: '13 — CONFIGURAÇÕES',
    items: [
      {
        id: 'nav-settings',
        label: 'Configurações',
        icon: Settings,
        scope: 'company',
        description: 'Parâmetros operacionais, fiscais, impressoras e locais',
        moduleNumber: '13',
        children: [
          {
            id: 'sub-set-general',
            label: 'Configurações',
            icon: Sliders,
            path: '/configuracoes',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Parâmetros gerais do tenant e preferências do sistema',
            viewType: 'settings',
          },
          {
            id: 'sub-set-companies',
            label: 'Empresas',
            icon: Building2,
            path: '/configuracoes/empresas',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Dados cadastrais da pessoa jurídica e matriz/filiais',
            viewType: 'list',
            createPath: '/configuracoes/empresas/adicionar',
          },
          {
            id: 'sub-set-locations',
            label: 'Locais Comerciais',
            icon: MapPin,
            path: '/configuracoes/locais',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Pontos de venda físicos, lojas e centros de distribuição',
            viewType: 'list',
            createPath: '/configuracoes/locais/adicionar',
          },
          {
            id: 'sub-set-invoices',
            label: 'Configurações de Faturas',
            icon: FileText,
            path: '/configuracoes/faturas',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Layouts de impressão de nota e esquemas de numeração',
            viewType: 'settings',
          },
          {
            id: 'sub-set-barcodes',
            label: 'Configurações de Código de Barras',
            icon: Barcode,
            path: '/configuracoes/codigo-barras',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Padrões de etiquetas (EAN-13, CODE-128, QR Code)',
            viewType: 'settings',
          },
          {
            id: 'sub-set-printers',
            label: 'Configurações de Impressora',
            icon: Printer,
            path: '/configuracoes/impressora',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Impressoras térmicas (ESC/POS) e impressoras padrão',
            viewType: 'settings',
          },
          {
            id: 'sub-set-taxes',
            label: 'Taxa de Imposto',
            icon: Percent,
            path: '/configuracoes/taxa-imposto',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Alíquotas fiscais e regras tributárias por estado',
            viewType: 'list',
            createPath: '/configuracoes/taxa-imposto/adicionar',
          },
          {
            id: 'sub-set-subscriptions',
            label: 'Assinaturas de Pacotes',
            icon: CreditCard,
            path: '/configuracoes/assinaturas',
            permission: 'empresa.configurar',
            scope: 'company',
            description: 'Histórico de renovação e plano contratado pela empresa',
            viewType: 'list',
          },
        ],
      },
    ],
  },
];

export const PLATFORM_NAVIGATION_CONFIG = OFFICIAL_NAVIGATION_CONFIG;

